FROM continuumio/miniconda3:latest

RUN conda create -n ds-gemma-course python=3.11 -y && \
    conda run -n ds-gemma-course conda install -y \
        jupyterlab=4 \
        numpy \
        pandas \
        matplotlib \
        seaborn \
        scikit-learn \
        scipy \
        statsmodels \
        ipykernel && \
    conda run -n ds-gemma-course pip install \
        ollama \
        ipywidgets \
        nbformat && \
    conda run -n ds-gemma-course python -m ipykernel install --name ds-gemma-course --display-name "DataPath (Python 3.11)"

ENV PATH /opt/conda/envs/ds-gemma-course/bin:$PATH

WORKDIR /home/jovyan

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
